FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . ./
RUN npm run build


FROM node:22-alpine AS production
WORKDIR /app
COPY --from=builder /app/package*.json ./
RUN npm ci --omit=dev --no-audit --no-fund && npm i -g pm2
COPY --from=builder /app/dist ./dist
COPY ecosystem.config.js ./ecosystem.config.js
EXPOSE 3001
ENTRYPOINT ["pm2-runtime", "start", "ecosystem.config.js"]
